sudo apt install ./hugo_extended_0.101.0_Linux-64bit.deb
sudo apt install arandr
sudo apt install composer
sudo apt install g++
sudo apt install git-flow
sudo apt install gnucash 
sudo apt install jq
sudo apt install make
sudo apt install meld
sudo apt install mycli
sudo apt install mysql-client
sudo apt install ncdu
sudo apt install neovim
sudo apt install pgcli
sudo apt install php
sudo apt install php-curl
sudo apt install php-gd
sudo apt install php-intl
sudo apt install php-xdebug
sudo apt install php-xml
sudo apt install php-zip
sudo apt install pv
sudo apt install python2
sudo apt install tmux
sudo apt install visidata
sudo apt install vlc
